name: multivariate_linear_regression
description: Multivariate linear regression for Dart with support for multiple outputs and optional intercept.
version: 0.1.1+1
homepage: https://github.com/noahweasley/Multivariate-Linear-Regression
repository: https://github.com/noahweasley/Multivariate-Linear-Regression

environment:
  sdk: ">=3.1.3 <4.0.0"

dev_dependencies:
  csv: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
